nix-community/lanzaboote

flake.nix, nix/lanzaboote.nix, rust/lanzatool/src/install.rs, rust/lanzatool/src/pe.rs
reduces the amount of TOCTOU we are having.
cc @nikstur @blitz
=> lanzatool: perform secure assembling for lanzaboote_image and PE wrapping

flake.lock, flake.nix, nix/uefi-run.nix, rust/lanzaboote/src/linux_loader.rs, rust/lanzaboote/src/pe_section.rs
This PR:
- fixes Clippy issues in lanzaboote (where possible),
- switches the build of all Rust components to Crane (Thanks to https://github.com/ipetkov/crane/pull/174 :tada:)
- enables clippy for lanzaboote in `nix flake check`
- drops the Naersk dependency
This PR will have some trivial merge conflicts with #21. But as they are easy to resolve, we can merge these PRs in any order.
=> Drop Naersk and Enable Clippy for lanzaboote

flake.lock, flake.nix, nix/lanzaboote.nix
without this users end up with multiple copies of nixpkgs, which cannot be overriden from the outside (follows only works on 1 level).
=> deduplicate flakes

rust/lanzatool/src/install.rs
This makes lanzaboote usable on master.
=> lanzatool: ignore malformed generations

flake.nix
When lanzatool is in the packages attr of the devShell, any compliation error in lanzatool means direnv cannot load the environment anymore. Then LSP support in your editor and even cargo in your shell is missing.
=> Move lanzatool to inputsFrom in devShell

rust/lanzatool/src/pe.rs, rust/lanzatool/src/signature.rs
Implements some requested changes from #34.
=> Some more lanzatool refactoring

flake.lock, flake.nix
In order to make multiple architectures and goodies like [pre-commit](https://github.com/cachix/pre-commit-hooks.nix) easier, I've switched out flakes.nix to using [flake-parts](https://flake.parts).
This also removes some hacks in getting the right `lanzatool` into our module. There should be no user-visible changes.
While I was here, I also updated our inputs.
Fixes #45.
=> Switch to flake-parts

docs/QUICK_START.md
This PR rewrites the quickstart docs to be more opinionated (less options) and more user focused (less developer-related information). 
It should be ok to follow for people who know their way around NixOS.
See the rendered version here: https://github.com/nix-community/lanzaboote/blob/docs/docs/QUICK_START.md
=> Rewrite Quickstart Docs

rust/lanzaboote/Cargo.lock, rust/lanzaboote/Cargo.toml, rust/lanzaboote/src/main.rs, rust/lanzatool/Cargo.lock, rust/lanzatool/Cargo.toml, rust/lanzatool/src/pe.rs
Using the sha2 crate instead of blake3 decreases the binary size of the stub by around 50%. 
From ~230K to ~90K
=> blake3 -> sha256

docs/QUICK_START.md, flake.nix, nix/modules/lanzaboote.nix, rust/tool/src/gc.rs, rust/tool/src/generation.rs, rust/tool/src/pe.rs
None of us are native English speakers. This PR enables automatic typo checks in our tree. I've also fixed all typos that it found.
=> Enable Typo Checks

rust/tool/src/install.rs, rust/tool/src/main.rs, rust/tool/src/pe.rs, rust/tool/src/utils.rs
Depends on #62 
Add an extension to TempDir that allows to create secure tempfiles. This
way, everything related to creating secure tempfiles is bundled in a
single place and can easily be reused.
=> Refactor tempdir: Add SecureTempDirExt

nix/modules/lanzaboote.nix, rust/tool/src/cli.rs, rust/tool/src/install.rs, rust/tool/src/os_release.rs, rust/tool/src/pe.rs, rust/tool/src/signature.rs, rust/tool/tests/common/mod.rs, rust/tool/tests/systemd_boot.rs
The process of installing systemd-boot is "smarter" because it now
considers a a few conditions instead of doing nothing if there is a file
at the deistination path. systemd-boot is now forcibly installed (i.e.
overwriting any file at the destination) if (1) there is no file at the
destination, OR (2) a newer version of systemd-boot is available, OR (3)
the signature of the file at the destination could not be verified.
Fixes part of #39 
Will produce a small and easy to fix merge conflict with #75
=> tool: smarter systemd-boot install 

rust/tool/src/install.rs, rust/tool/src/main.rs, rust/tool/src/systemd.rs
To make handling systemd versions more robust, they are parsed into a u32 tuple instead of an f32. Additionally, some unit tests for correct parsing and comparing of versions are added.
=> tool: make systemd version parsing robust

nix/modules/lanzaboote.nix, nix/tests/lanzaboote.nix, rust/tool/src/cli.rs, rust/tool/src/esp.rs, rust/tool/src/install.rs, rust/tool/tests/common/mod.rs, rust/tool/tests/gc.rs
To minimize the number of arguments passed to `lzbt`, the loader config is assembled outside `lzbt` and passed as a single argument.
Instead of reimplementing `consoleMode` under the `lanzaboote` namespace, `config.loader.systemd-boot.consoleMode` is reused as is.
Implements #72
=> tool: write systemd-boot loader.conf

rust/stub/src/main.rs, rust/stub/src/pe_loader.rs, rust/stub/src/uefi_helpers.rs, rust/tool/src/install.rs
Using a malicious boot loader specification entry, the kernel could be instructed to load untrusted initrds in two ways:
* Since the kernel was signed, it could be loaded directly, with an arbitrary initrd (since neither systemd-boot nor Linux verify initrds).
* The cmdline our stub received was passed on to the kernel. By loading the stub indirectly via boot loader specification, this could be abused to point the kernel to an arbitrary initrd, as well as instructing it to perform various other fun stuff.
To prevent these security bypasses, the following solution is implemented:
* Use a custom PE loader, just enough to load the kernel, in order not to rely on `LoadImage`. This loader does not need to verify signatures, because we already confirmed using the hash that the kernel is …
=> Prevent loading of untrusted initrds

docs/QUICK_START.md
Newcomers should at least be told that there are more steps to be taken to get anything out of Secure Boot. I've added a short statement that hopefully gives a small hint that Secure Boot security is a complex topic.
=> Add Security Disclaimer in Quickstart Docs

nix/tests/lanzaboote.nix
Now that we don't sign the kernel anymore, we need to manually invalidate its checksum.
This is a regression from #75. See https://github.com/nix-community/lanzaboote/pull/75#issuecomment-1413953437.
=> Fix CI Regression after Linux Loader Fix

nix/tests/lanzaboote.nix, rust/stub/src/main.rs
This PR makes the stub fall back to UEFI `LoadImage` when we detect a hash mismatch in the stub. This has the effect of failing boot when Secure Boot is enabled (because of the security violation of trying to load an unsigned kernel) and making the boot work if Secure Boot is off.
This would elegantly fix #58 without having to embed another PE binary. It feels a bit "sneaky" though. Should we add a compile time parameter to disable this functionality for the more security-inclined or is this ok?
Fixes #58.
=> Ignore Integrity Checks without Secure Boot

docs/QUICK_START.md
Our quickstart instructions are out of date, as shown by #92. Also since #91 we have better recovery options.
=> Update Sharp Edges in Quickstart Docs

rust/tool/src/generation.rs, rust/tool/tests/common/mod.rs
Read the build time from generation symlinks in /nix/var/nix/profiles
instead of from the underlying derivation. The derivation build time
will always be a UNIX epoch of 0 because of the `nix-build` sandbox,
which is useless for identifying when a generation was created.
Closes #95
=> tool: read build time from symlink

rust/tool/tests/common/mod.rs, rust/tool/tests/gc.rs, rust/tool/tests/systemd_boot.rs
This PR is part of a larger series which is supposed to be merged in order but is broken up into multiple pieces to make review easier. It is supposed to be merged in this order:
(#108) -> #107 -> #110 -> #109
Make the utility functions reusable by moving them to the common module.
=> tool: make some utility test functions reusable

docs/QUICK_START.md
The Flakes configuration fragment in the quickstart documentation was not self-contained and implicitly assumed that a Flakes intput needs to be added. Make this more obvious.
Fixes #104.
=> Add a More Complete Flakes Fragment for Quickstart

rust/tool/Cargo.lock, rust/tool/Cargo.toml, rust/tool/src/install.rs, rust/tool/src/pe.rs, rust/tool/src/utils.rs
This PR is part of a larger series which is supposed to be merged in order but is broken up into multiple pieces to make review easier. It is supposed to be merged in this order:
#108 -> (#107) -> #110 -> #109
Using random names for tempfiles makes handling them easier. It reduces the amount of noise in the code because no custom name needs to be provided for each tempfile. The names were not really useful in any case.
It also does not burden the developer with ensuring uniqueness of names. This is relevant when files for multiple generations need to be stored in the same directory (e.g. because they need to be accessed after handling one generation).
Out of an abundance of caution, 32 random alphanumeric characters are chosen for each filename. The tempfile crate, in comparison, only …
=> tool: use random names for secure tempfiles

rust/stub/Cargo.lock, rust/stub/Cargo.toml, rust/stub/src/linux_loader.rs
This PR updates the Rust dependencies of the stub. Most notably, it updates to the latest version of the `uefi` crate, which brings some minor breaking changes.
=> Update Dependencies of Stub

rust/tool/src/install.rs, rust/tool/src/pe.rs, rust/tool/src/utils.rs, rust/tool/tests/common/mod.rs, rust/tool/tests/install.rs
This PR is part of a larger series which is supposed to be merged in order but is broken up into multiple pieces to make review easier. It is supposed to be merged in this order:
#108 -> #107 -> (#110) -> #109
This change ensures that the files on the ESP are correct and up to date by (1) first collecting all artifacts across generations and then writing them all at once, and (2) by comparing the file hash of the files on the ESP against the expected values. Only if these do not match, a file is copied or  overwritten.
More information about the nuances of this are in comments in the code or in the commit messages.
Closes #39
Depends on #107 #108
=> tool: ensure correct up to date files in the ESP

nix/tests/lanzaboote.nix, rust/tool/src/install.rs
This PR is part of a larger series which is supposed to be merged in order but is broken up into multiple pieces to make review easier. It is supposed to be merged in this order:
#108 -> #107 -> #110 -> (#109)
To correctly overwrite existing initrd with newer secrets (from newer
generations), the links need to be sorted from oldest generation to
newest.
Closes #103 
Depends on #110
=> tool: correctly update initrd secrets

rust/stub/Cargo.toml, rust/stub/src/main.rs
This PR is an alternative to #87. The end result is the same: When everything goes well, lanzaboote gives no output (fixing #84).
The approach is different in that we don't allow any runtime modification of logging level. The release build will only print warnings and errors. I think too much configurability is not really helping and just introduces complexity which we can avoid.
Closes #84.
=> Minimalistic Logging Support

rust/tool/src/install.rs
Due to the use of hash maps, the order of file installation was not deterministic. I've changed the code the use BTreeMaps instead, which makes this deterministic. While I was here, I tried to simplify the code a bit.
Reported-by: @RaitoBezarius
=> Make File Installation Order Deterministic

nix/tests/lanzaboote.nix
The way the test was implemented previously did not make it fail if no secret was appended to the initrd. Now it is implemented similary to the initrd-secrets test in Nixpkgs and works correctly.
Closes #106
=> tests: correctly test appending secret to initrd

README.md, nix/modules/lanzaboote.nix
Closes #85
```
$ sudo sbctl verify
Verifying file database and EFI images in /boot...
✓ /boot/EFI/BOOT/BOOTX64.EFI is signed
✓ /boot/EFI/Linux/nixos-generation-553.efi is signed
✓ /boot/EFI/Linux/nixos-generation-554.efi is signed
✓ /boot/EFI/Linux/nixos-generation-555.efi is signed
✓ /boot/EFI/Linux/nixos-generation-556.efi is signed
✓ /boot/EFI/Linux/nixos-generation-557.efi is signed
✓ /boot/EFI/Linux/nixos-generation-558.efi is signed
✓ /boot/EFI/Linux/nixos-generation-559.efi is signed
✓ /boot/EFI/Linux/nixos-generation-560.efi is signed
✓ /boot/EFI/Linux/nixos-generation-561.efi is signed
✓ /boot/EFI/Linux/nixos-generation-562.efi is signed
✓ /boot/EFI/Linux/nixos-generation-563.efi is signed
✓ /boot/EFI/nixos/fwupdx64.efi is signed
✓ /boot/EFI/systemd/systemd-bootx64.efi is signed …
```
=> Properly handle fwupd update capsules

README.md, nix/modules/lanzaboote.nix
Reverts nix-community/lanzaboote#113. Users have reported issues:
```
error: The option `environment.etc."fwupd/uefi_capsule.conf".source' has conflicting definition values:
- In `/nix/store/s2lni0idfkhs0lcnr8walzhdqzarfb0m-source/nixos/modules/system/etc/etc.nix': <derivation etc-uefi_capsule.conf>
- In `/nix/store/s2lni0idfkhs0lcnr8walzhdqzarfb0m-source/nixos/modules/services/hardware/fwupd.nix': "/nix/store/nxv27wliyqqdxvp44mx715d2v568k9ym-fwupd-1.8.10/etc/fwupd/uefi_capsule.conf"
Use `lib.mkForce value` or `lib.mkDefault value` to change the priority on any of these definitions.
```
=> Revert "Properly handle fwupd update capsules"

rust/stub/src/main.rs, rust/stub/src/pe_section.rs, rust/stub/src/uefi_helpers.rs
... because this might not work, if we were not loaded from a file system. It also removes the issue where we might not load the signed image that was actually loaded. Parsing the PE file we are currently executing from does not really fit in to Rust's safety model. If the `unsafe` block I added is objectionable, we can copy the image in memory and parse it from there.
Fixes #123.
=> Don't Reload Stub from the File System

README.md, flake.lock, flake.nix, nix/modules/lanzaboote.nix
This is a mostly verbatim copy of #113 (credit to @dasJ for most all of this) that has been updated to use NixOS/nixpkgs#220555 (which has hit nixos-unstable now). It has been successfully tested with a BIOS update (with secureboot enforcing) on a 12th-gen Framework
Also we probably should update the lockfile in this repo first (or let Renovate bot handle it), since this will probably fail eval without that PR
=> Properly handle fwupd update capsules, take 2

nix/modules/lanzaboote.nix, nix/tests/lanzaboote.nix
This commit adds settings key for configuring systemd-boot to the lanzaboot nixos module. The are couple of the default values that are set from the usual nixos boot.loader.systemd-boot options, they are merged with the user defined configuration.
This commit modifies default loader.conf to boot into the latest nixos generation by default, for when you have other operating systems installed.
Primary reason behind this PR is to allow extensible loader configuration.
---
This closes https://github.com/nix-community/lanzaboote/issues/133
Is this too complicated? What do you think?
=> nixos-module: add settings key for the loader.conf

rust/tool/src/install.rs
Fixes #140
My theory is that from the last tool update sbattach made removing the image signature from the signed image during the resign test match the initial input. This likely caused the condition at https://github.com/nix-community/lanzaboote/blob/master/rust/tool/src/install.rs#L440 to return false for what I assume is the first time.
I am a bit confused for why this condition exists as it should in theory only return false if the EFI file matches the unsigned input unless I have missed something. The only way to implement that check I can think off is to verify it has been correctly signed, remove the signature table and then compare with the input, at which point it becomes easier to just always sign.
=> tool: drop buggy condition for when to sign

flake.nix, rust/stub/Cargo.lock, rust/stub/Cargo.toml, rust/stub/rust-toolchain.toml, rust/stub/src/main.rs
The stub (and the tool) uses a stable Rust compiler.
=> stub: make it compatible with a stable Rust compiler (≥ 1.68.x)

rust/stub/src/pe_loader.rs
People reportedly want to compile the stub on i686 and AArch64 platforms for testing. Make compilation possible by providing proper `flush_instruction_cache` implementations on these platforms. For x86 (just as x86_64), this is a no-op, because Intel made the instruction cache coherent for compatibility with code that was written before caches existed.
For AArch64, adapt the procedure from their manual to multiple instructions.
=> stub: implement `flush_instruction_cache` on i686 and AArch64

flake.lock
Update Rust Overlay for #150.
Flake lock file updates:
• Updated input 'rust-overlay':
'github:oxalica/rust-overlay/45c2ed9dd1397526dad35fc867c43955d87f9f3f' (2023-04-10)
→ 'github:oxalica/rust-overlay/2c417c0460b788328220120c698630947547ee83' (2023-04-22)
=> Bump Rust Overlay

rust/tool/src/install.rs
lzbt currently happily nukes all boot entries, if it can't parse any bootspecs. With the upcoming incompatible bootspec change, this might be a problem that's worth avoiding. :)
I changed lzbt to fail hard in case, it can't generate any boot items.
Closes #154. Relates to #148.
=> Avoid Unbootable System on Bootspec Changes

rust/tool/src/install.rs
The message about malformed generations should semantically be a warning. However, since users might have hundreds of old and thus malformed generations and can do little about it, this should remain a debug message. This way the user is not spammed with no-op warnings while still enabling debugging.
This reverts the change to the log level made in #155
=> tool: revert log level of malformed gens

rust/tool/src/generation.rs, rust/tool/tests/common/mod.rs, rust/tool/tests/os_release.rs
We kinda need this because XFS doesn't appear to support birth time:
```
running 15 tests
test esp::tests::nixos_path_creates_correct_filename_from_nix_store_path ... ok
test gc::tests::delete_empty_unused_directory ... ok
test gc::tests::delete_unused_directory_with_unused_file_inside ... ok
test gc::tests::delete_unused_file ... ok
test generation::tests::parse_version_correctly ... ok
test gc::tests::keep_used_file ... ok
test os_release::tests::escaping_works ... ok
test gc::tests::only_delete_filtered_unused_files ... ok
test os_release::tests::parses_correctly_from_str ... ok
test gc::tests::keep_used_directory_with_used_and_unused_file ... ok
test pe::tests::convert_to_valid_uefi_path ... ok
test pe::tests::convert_to_valid_uefi_path_relative_to_esp ... ok
test …
```
=> tool: Switch back to mtime

rust/tool/Cargo.lock, rust/tool/Cargo.toml, rust/tool/src/install.rs
Disable GC if there are any malformed gens to avoid catastrophic failure when there are upstream changes to NixOS that are not handled in lzbt.
Suggested by @alois31 
Closes #127
=> tool: disable gc in the presence of malformed gens

flake.lock, nix/tests/lanzaboote.nix, rust/tool/Cargo.lock, rust/tool/Cargo.toml, rust/tool/src/esp.rs, rust/tool/src/generation.rs, rust/tool/src/install.rs, rust/tool/src/os_release.rs, rust/tool/tests/common/mod.rs
This brings the final (accepted) changes of RFC-0125 and render lanzaboote unable to read the previous generations' bootspec anymore.
=> bootspec: RFC-0125 final changes

nix/tests/lanzaboote.nix, rust/tool/src/generation.rs
Bootspec has a mechanism called synthesis where you can synthesize bootspecs if they are not present based on the generation link only.
This is useful for "vanilla bootspec" which does not contain any extensions, as this is what we do right now.
If we need extensions, we can also implement our synthesis mechanism on the top of it.
Enabling synthesis gives us the superpower to support non-bootspec users. :-)
=> feat: enable synthesis support

nix/tests/lanzaboote.nix, rust/stub/Cargo.lock, rust/stub/Cargo.toml, rust/stub/src/efivars.rs, rust/stub/src/main.rs
@nikstur be happy now :>
We only need to polyfill some features, @blitz let me know what is the potential for upstreaming to uefi-rs.
internal todolist:
- TPM measurements are out of scope for this PR and variables related to them too.
- Random seed support is out of scope for this PR
This implements a substantial part of #94.
=> feat: minimal poc for exporting UEFI variables à la sd-boot

flake.nix, rust/stub/Cargo.lock, rust/stub/Cargo.toml, rust/tool/Cargo.lock, rust/tool/Cargo.toml
We didn't do it, now we do it and we have the nifty `cargo-release`, some good automation could be done for cutting releases, etc.
=> chore: sync our crates version to latest tag

rust/tool/Cargo.lock, rust/tool/Cargo.toml, rust/tool/src/generation.rs
This uses the latest advances in bootspec for a cleaner code.
Wait until @cole-h figure out for TryFrom impls and cut a release.
=> tool(bootspec): remove boilerplate with newest bootspec

rust/stub/Cargo.lock, rust/stub/Cargo.toml, rust/stub/src/efivars.rs, rust/stub/src/linux_loader.rs, rust/stub/src/main.rs, rust/stub/src/uefi_helpers.rs
It simplifies our filesystem handling.
=> deps: update to uefi-rs 0.21.0

flake.nix
Add a proper description to flake.
Use nativeCheckInputs instead of checkInputs because it is more
semantically correct even if checkInputs works with Crane.
=> Cleanup flake

docs/QUICK_START.md
Following the quick start guide causes the Forbidden Signature Database (dbx) to be cleared while having Microsoft keys enrolled. 
fwupdmgr does not seem to update the dbx after manually clearing it.
This patch proposes to add a bit of explaination and some warnings to the documentation.
=> docs: add precision about dbx and OptionROMs

README.md
We now have bootspec enabled by default for 23.05+.
=> docs: update upstreaming state

README.md, flake.nix, nix/modules/uki.nix, nix/tests/stub.nix, rust/stub/Cargo.toml, rust/stub/src/common.rs, rust/stub/src/fat.rs, rust/stub/src/main.rs, rust/stub/src/thin.rs
A compile time feature is introduced that allows to build "fat" stubs that can be used to build "fat" UKIs. "fat" here means that the actual kernel and initrd are embedded in the PE binary, not only the file path and hash. This brings us one step closer to feature partiy with systemd-stub and thus one step closer to replacing it fully. Such a "fat" or "real" UKI is also interesting for image-based deployments of NixOS.
The new tests use `runTest` the future of testing in NixOS. See https://github.com/NixOS/nixpkgs/pull/230523
Thank you @RaitoBezarius and especially @blitz (and all the others who have contributed). The stub code is so well structured and well commented so that it was easy to extend even without any prior experience in UEFI or no-std environments.
=> stub: add fat variant

rust/stub/Cargo.lock, rust/stub/Cargo.toml
This upgrade is necessary to avoid borking boot on bad UEFI implementations.
=> stub: upgrade to uefi-rs 0.22.0

flake.nix
```
error: attribute 'hostPlatform' missing
at /nix/store/k7h8k8whqw64rmsg6yhkmmdc82lkczc6-source/flake.nix:66:27:
65|               # linuxArch is wrong here, it will yield arm64 instead of aarch64.
66|               config = "${pkgs.hostPlatform.qemuArch}-windows";
|                           ^
67|               rustc.config = "${pkgs.hostPlatform.qemuArch}-unknown-uefi";
Did you mean rustPlatform?
```
=> Fix eval when aliases are disabled

docs/QUICK_START.md
Since this is the default now there should probably be a mention that you can skip this with a somewhat recent system. 
Note: There should probably be a version number stated of the version that made bootspec on by default but I don't know which version this was so :shrug:
=> update QUICK_START.md bootspec

docs/QUICK_START.md
The flake setup previously suggested master implicitly, we use the latest known release.
=> docs: suggest to track released versions rather than master 

flake.nix
As we use Hercules CI with nix-community builder, our CI sends the stuff there all the time.
Now, let's make everyone benefit from it.
=> flake: offer nix-community cache as a suggested substituter

rust/stub/Cargo.lock, rust/stub/Cargo.toml, rust/tool/Cargo.lock, rust/tool/Cargo.toml
The goblin update to 0.7.1 breaks the stub and renovate is annoying me, so I want to merge the updates that work and take care of goblin  later.
=> Update all dependencies besides goblin 

docs/QUICK_START.md
Reverts nix-community/lanzaboote#207 because it tells users to use a 0.3 branch on nixpkgs
=> Revert "docs: suggest to track released versions rather than master "

flake.nix
This fixes the following error:
....
cargo-auditable>    Doc-tests auditable-extract
cargo-auditable> error: doctest failed, to rerun pass `-p auditable-extract --doc`
cargo-auditable>
cargo-auditable> Caused by:
cargo-auditable>   could not execute process `rustdoc --edition=2018 --crate-type lib --crate-name auditable_extract --test /build/source/auditable-extract/src/lib.rs --target x86_64-unknown-linux-gnu -L dependency=/build/source/target/x86_64-unknown-linux-gnu/release/deps -L dependency=/build/source/target/release/deps --test-args --test-threads=96 --extern auditable_extract=/build/source/target/x86_64-unknown-linux-gnu/release/deps/libauditable_extract-dd1904617e4b78db.rlib --extern binfarce=/build/source/target/x86_64-unknown-linux-gnu/release/deps/libbinfarce-2ba09d21aed0de1a. …
=> Fix lzbt build with recent nixos-unstable

flake.nix
nixConfig is not a nice abstraction because it imperatively changes your system. However this also does not work correctly without extra changes to your system (i.e. your NixOS configuration). Thus it is removed.
=> flake: remove nixConfig

flake.lock, flake.nix, nix/modules/lanzaboote.nix, rust/tool/shared/src/architecture.rs, rust/tool/shared/src/esp.rs, rust/tool/shared/src/lib.rs, rust/tool/systemd/src/architecture.rs, rust/tool/systemd/src/cli.rs, rust/tool/systemd/src/esp.rs, rust/tool/systemd/src/install.rs, rust/tool/systemd/src/lib.rs, rust/tool/systemd/src/main.rs, rust/tool/systemd/tests/common/mod.rs, rust/tool/systemd/tests/systemd_boot.rs, rust/uefi/rust-toolchain.toml
This introduces a basic support of AArch64 through the introduction of System structures to write the correct filenames based on UEFI "specifications".
=> feat: support for AArch64

flake.nix
Fixes 
```
error: attribute 'hostPlatform' missing
at /nix/store/8hqjsxybh8fvkij104linyyp3gi3c560-source/flake.nix:82:27:
81|         let
82|           rustTarget = "${pkgs.hostPlatform.qemuArch}-unknown-uefi";
|                           ^
83|           pkgs = import nixpkgs {
Did you mean rustPlatform?
```
regressed in #31
=> Fix eval in flakes when aliases are disabled

nix/modules/uki.nix
Previously, we were not on recent enough nixpkgs to see the new `withBootloader` flag which is required to build ukify.
Fixes the test infrastructure for the UKI part.
=> nix/modules/uki: fix ukify build

README.md, docs/QUICK_START.md, docs/TROUBLESHOOTING.md
Running out of space on the ESP is an error that commonly happens. Document how to proceed in this case.
Furthermore, in case the ESP gets corrupted, the system needs to be recovered. Document how to do this.
These are the parts of the documentation from https://github.com/nix-community/lanzaboote/pull/204 that don't actually belong there.
=> docs: Add troubleshooting documentation

docs/TROUBLESHOOTING.md, nix/tests/lanzaboote.nix, rust/tool/Cargo.lock, rust/tool/shared/src/esp.rs, rust/tool/shared/src/generation.rs, rust/tool/shared/src/pe.rs, rust/tool/systemd/Cargo.toml, rust/tool/systemd/src/install.rs, rust/tool/systemd/tests/common/mod.rs, rust/tool/systemd/tests/gc.rs, rust/tool/systemd/tests/install.rs, rust/tool/systemd/tests/os_release.rs
Currently, whenever installation is performed, the stubs for all generations are re-generated with the newest stub version and written to the esp. If a newer stub causes breakage on a specific machine (e.g. by bad interactions with buggy firmware), this leads to all generations becoming unbootable. Since at least one generation was bootable in the past, this problem can be avoided by avoiding the re-writing of already existing stubs. (Of course, this problem can still happen with a bad systemd-boot update, but we should not introduce a needless second single point of failure).
Similarly, whenever installation is performed, all kernels and initrds are currently collected in a temporary directory, compared and written to the ESP if they don't already exist or mismatch. This can similarly …
=> Stop most overwriting in the ESP

rust/uefi/Cargo.lock, rust/uefi/linux-bootloader/Cargo.toml, rust/uefi/linux-bootloader/src/efivars.rs, rust/uefi/stub/Cargo.toml, rust/uefi/stub/src/thin.rs
This updates our UEFI dependencies by dealing with some breaking changes.
Fixes #234. Unblocks #196.
=> stub: update to latest uefi crates

nix/modules/lanzaboote.nix
This includes the options of all modules used in the evaluation, not just the ones from `<nixpkgs/nixos>` in the local manual.
Right now this breaks with
error: attribute 'loader' missing
at /nix/store/wf59fvxch3l5s7x0pnpfv7b26q6y010x-source/nix/modules/lanzaboote.nix:26:17:
25|     configurationLimit = mkOption {
26|       default = config.boot.loader.systemd-boot.configurationLimit;
|                 ^
27|       example = 120;
I'm not sure what's up with `config.boot.loader` (had the exact same issue with `disko`), but using `defaultText` is the common workaround for that.
=> Fix build with `documentation.nixos.includeAllModules = true;`

rust/uefi/linux-bootloader/Cargo.toml
This PR works around a goblin update problem and hopefully finally unblocks #196.
See #237 for context.
=> stub: pin to current goblin version

flake.lock, flake.nix, nix/tests/lanzaboote.nix
EDK2 seems to have broken Secure Boot with their recent release. Pin the older version for now to unblock #216.
See #240 for context.
=> Pin EDK2 202305

rust/tool/shared/src/generation.rs, rust/tool/shared/src/os_release.rs, rust/tool/systemd/src/install.rs, rust/tool/systemd/tests/os_release.rs
systemd-boot only displays the `VERSION_ID` for generations where the name is not unique. This leads to users being confused (#220).
Fix by including the version in the name. This makes names unique and the systemd-boot menu will now look consistent.
Fixes #220.
=> Consistently Display Generations in systemd-boot

docs/QUICK_START.md
Not sure if this is redundant but for nixos installation, I like to be extra verbose since it's often read by new NixOS users.
=> docs: clarify migration path for new installations

nix/tests/lanzaboote.nix, nix/tests/stub.nix
By default, it is one hour but our CI cannot handle that many VM tests, so we switch to 5 minutes default timeouts.
=> tests: add 5 minutes default timeout

flake.nix
As flake-parts doesn't really support a concept of limited supported system (e.g. system for which we don't have CI), we need to fix up the final outputs to move the unsupported checks to another place where CI won't run them.
=> feat(flake): perform final fixups to the flake outputs

rust/uefi/.cargo/config
The linker embeds a timestamp into our UEFI stub. objdump -p reports:
```
Time/Date               Mon Nov 13 20:02:35 2023
```
With `/Brepro` we get the following instead:
```
Time/Date		d597e888	(This is a reproducible build file hash, not a timestamp)
```
Fixes #260
=> Remove Nondeterminism in Stub

flake.nix
Alas, I don't know how to do this properly with Flakes, it is a sad state of affairs.
Fixes #264.
=> flake: remove "moving away the `unsupportedChecks`"

rust/tool/systemd/src/install.rs
Currently, because `lanzatool` fails loudly if the `append_initrd_secrets` fails for one generation, the only way out if a user ever misconfigures the `boot.initrd.secrets` option is to completely remove the generation. 
This behaviour is fine but very misleading for an innocent user (me yesterday): they will continue to edit their `boot.initrd.secrets` option in order to fix the failure but still be met by the same error. This change adds a more helpful error message.
=> add more helpful message in case of append_initrd_secrets script failure

flake.nix, rust/uefi/linux-bootloader/src/pe_loader.rs, rust/uefi/rust-toolchain.toml, rust/uefi/stub/src/fat.rs
- Remove sbctl from devShell as its annoying to rebuild
- Update Rust 1.70 -> 1.75 (fixes new clippy warnings)
=> Small fixes & updates

nix/tests/lanzaboote.nix, rust/tool/shared/src/pe.rs, rust/tool/systemd/src/install.rs, rust/uefi/stub/src/thin.rs
This PR renames section names in our thin stub:
- `.kernelp` -> `.linux`
- `.initrdp` -> `.initrd`
- `.kernelh` -> `.linuxh` (for consistency)
This allows `bootctl kernel-inspect` to properly parse our UKIs. Before it would not recognize them as UKIs.
We basically have to satisfy this function in systemd: https://github.com/systemd/systemd/blob/main/src/shared/pe-binary.c#L230
@nikstur Does this have backward compatibility issues?
Fixes #296. Relates to #295.
=> UKI Compatibility for systemd 255

rust/uefi/Cargo.lock, rust/uefi/Cargo.toml, rust/uefi/pio/Cargo.toml, rust/uefi/pio/src/cursor.rs, rust/uefi/pio/src/errors.rs, rust/uefi/pio/src/lib.rs, rust/uefi/pio/src/packer.rs, rust/uefi/pio/src/writer.rs, rust/uefi/pio/tests/read_write.rs
This library is in its own directory to maintain as a separate project.
This is useful for the systemd-stub parity when we need to write CPIOs when we assemble dynamic credentials or system extensions.
=> feat(cpio): introduce `pio`, a library to write CPIO in `alloc` contexts

rust/uefi/stub/src/fat.rs, rust/uefi/stub/src/main.rs, rust/uefi/stub/src/thin.rs
With this feature, it is now possible to load dynamic initrds (possibly read from filesystem or generated on the fly)
and extend existing initrds.
This feature will be useful to implement addons in the future.
=> stub(*): support dynamic initrds

flake.lock, nix/tests/lanzaboote.nix
I think the newest OVMF is working now, so we don't need to fetch the old version anymore.
Instead of doing custom overrides, we can also just use OVMFFull which includes all the necessary parts.
If this works, it supersedes #310
=> tests: remove custom OVMF overrides

docs/QUICK_START.md
I tested Lanzaboote yesterday and was confused as there was no obvious option to "enter Setup Mode". With some Google-fu I found out that [erasing the Platform Key](https://wiki.archlinux.org/title/Unified_Extensible_Firmware_Interface/Secure_Boot#Putting_firmware_in_%22Setup_Mode%22) has the same effect.
=> Elaborate on entering Setup Mode

nix/modules/lanzaboote.nix
See the following for more info:
- https://github.com/NixOS/nixpkgs/issues/300735 for the tracking issue
- https://github.com/NixOS/nixpkgs/pull/237557 for the changes in the manual
- https://github.com/NixOS/nixpkgs/pull/303841 removes all `lib.mdDoc` uses (13k changes)
- https://github.com/NixOS/nixpkgs/pull/304277 adds `mdDoc` back, fixes the warning & sets an explicit timeline for the final removal:
> lib.mdDoc will be removed from nixpkgs in 24.11. Option descriptions are now in Markdown by default; you can remove any remaining uses of lib.mdDoc.
=> fix: remove deprecated lib.mdDoc

nix/tests/default.nix, nix/tests/lanzaboote/common/efivariables-helper.nix, nix/tests/lanzaboote/export-efivars-tpm.nix, nix/tests/lanzaboote/export-efivars.nix, nix/tests/lanzaboote/systemd-measured-uki.nix, nix/tests/lanzaboote/systemd-pcrlock.nix, rust/uefi/linux-bootloader/src/measure.rs, rust/uefi/linux-bootloader/src/tpm.rs
Lanzaboote was not storing some strings in UTF-16 as required. This results in garbled output in systemd-pcrlock, for example. 
Note: systemd-pcrlock itself is not operational in NixOS without further tinkering, but that is beyond the scope of this PR. With this PR, systemd-pcrlock shows descriptions correctly and systemd-measure does not complain that the stub didn't measure correctly.
=> Fix encoding issues

flake.lock
Flake lock file updates:
• Updated input 'crane':
'github:ipetkov/crane/55e7754ec31dac78980c8be45f8a28e80e370946' (2024-06-04)
→ 'github:ipetkov/crane/a3f0c63eed74a516298932b9b1627dd80b9c3892' (2024-06-11)
This pulls in fixes discussed in https://github.com/ipetkov/crane/issues/612. See also https://github.com/nix-community/lanzaboote/pull/355 for a previous attempt by yours truly at fixing it. Note that this flake update does not come with the previous downside of removing source filtering.
Tested:
```
$ nix store gc && nix flake check --no-build github:nix-community/lanzaboote
14 store paths deleted, 233.67 MiB freed
error:
… while checking flake output 'packages'
at «none»:0: (source not available)
… while checking the derivation 'packages.x86_64-linux.tool'
at «none»:0: (source not …
```
=> Update the crane flake input to prevent IFDs when building the UEFI stub

CHANGELOG.md, nix/modules/lanzaboote.nix, nix/tests/lanzaboote/basic.nix, nix/tests/lanzaboote/common/lanzaboote.nix, rust/tool/Cargo.lock, rust/tool/shared/Cargo.toml, rust/tool/shared/src/generation.rs, rust/tool/shared/src/os_release.rs, rust/tool/systemd/tests/integration/common.rs, rust/tool/systemd/tests/integration/gc.rs, rust/tool/systemd/tests/integration/install.rs, rust/tool/systemd/tests/integration/main.rs, rust/tool/systemd/tests/integration/os_release.rs, rust/tool/systemd/tests/integration/systemd_boot.rs
- Reorganize integration tests
- ~~Reorganize crates (names and directories) to be more consistent~~
- Set boot loader timeout to 0 to speed up NixOS tests
- Add `boot.lanzaboote.sortKey` option. Closes #349 
Review commit by commit.
=> Reorganize tests & add sort-key support

README.md
The @ukvly.org server died earlier this year, but the room is still alive at #secure-boot:nixos.org.
=> Fix Matrix Room Link

rust/uefi/Cargo.lock, rust/uefi/Cargo.toml, rust/uefi/linux-bootloader/Cargo.toml, rust/uefi/linux-bootloader/src/companions.rs, rust/uefi/linux-bootloader/src/cpio.rs, rust/uefi/linux-bootloader/src/lib.rs, rust/uefi/linux-bootloader/src/measure.rs, rust/uefi/linux-bootloader/src/uefi_helpers.rs, rust/uefi/stub/Cargo.toml, rust/uefi/stub/src/main.rs, rust/uefi/stub/src/thin.rs
This makes use of the pio library to discover, charge, measures companions.
Depends on the dynamic initrds PR: https://github.com/nix-community/lanzaboote/pull/305.
=> stub: load companions

rust/uefi/Cargo.lock, rust/uefi/linux-bootloader/Cargo.toml, rust/uefi/linux-bootloader/src/tpm.rs, rust/uefi/stub/Cargo.toml, rust/uefi/stub/src/fat.rs, rust/uefi/stub/src/main.rs, rust/uefi/stub/src/thin.rs
A few code changes were needed where the API has changed since 0.29.0:
* `uefi::helpers::init` no longer takes an argument.
* The `PcrEventInputs::new_in_buffer` API changed. In addition, there is now a `PcrEventInputs::new_in_box` constructor that allocates a correctly-sized buffer. Switch to that constructor.
=> chore(deps): update uefi to 0.31.0

rust/uefi/linux-bootloader/src/efivars.rs
Rather than calling get_variable_size, allocating a vec, and then reading into it, use a fixed-size buffer. The behavior is unchanged, just a little simpler.
Also added a summary of the error behavior to the docstring.
=> linux-bootloader: simplify get_loader_features

flake.nix, nix/modules/lanzaboote.nix, nix/modules/uki.nix
This is a minor change in coding style that removes path references replacing them with `lib.getExe`.
This makes executable references less dependent on binary names.
Major advantage: the `cfg.package` option doesn't require the binary name to be "lzbt" anymore.
=> Minor coding style fix: lib.getExe instead of ${bin}/bin/bin

rust/uefi/linux-bootloader/src/efivars.rs, rust/uefi/stub/src/common.rs, rust/uefi/stub/src/fat.rs, rust/uefi/stub/src/main.rs, rust/uefi/stub/src/thin.rs
uefi-rs is transitioning away from explicit `BootServices` and `RuntimeServices` structs, plain functions will be used instead. See https://github.com/rust-osdev/uefi-rs/blob/main/docs/funcs_migration.md for more details.
To keep the review more manageable, this PR only updates uses of `RuntimeServices`; I'll follow up with PRs for `BootServices`.
=> Replace uses of the RuntimeServices struct

rust/uefi/linux-bootloader/src/efivars.rs, rust/uefi/linux-bootloader/src/measure.rs
Missed a few spots in the previous PR.
=> linux-bootloader: Clean up remaining uses of RuntimeServices

rust/uefi/linux-bootloader/src/companions.rs, rust/uefi/linux-bootloader/src/efivars.rs, rust/uefi/linux-bootloader/src/linux_loader.rs, rust/uefi/linux-bootloader/src/measure.rs, rust/uefi/linux-bootloader/src/pe_loader.rs, rust/uefi/linux-bootloader/src/tpm.rs, rust/uefi/linux-bootloader/src/uefi_helpers.rs, rust/uefi/stub/src/common.rs, rust/uefi/stub/src/fat.rs, rust/uefi/stub/src/main.rs, rust/uefi/stub/src/thin.rs
Continuing the migration from previous PRs, clean up most uses of `BootServices` and `boot_services()`. In a couple place it's still needed for the uefi-0.31 API; those can be cleaned up when updating to uefi-0.32.
=> Drop most uses of `BootServices`

rust/uefi/linux-bootloader/src/efivars.rs, rust/uefi/linux-bootloader/src/pe_loader.rs, rust/uefi/stub/src/common.rs, rust/uefi/stub/src/fat.rs, rust/uefi/stub/src/main.rs, rust/uefi/stub/src/thin.rs
Continuing to smooth the way for updating to uefi-0.32.
=> Drop most uses of `SystemTable`

rust/tool/systemd/src/install.rs
Old:                                                                                                                                                        
building the system configuration...                                                                                                                        
Installing Lanzaboote to "/boot"...                                                                                                                         
Failed to install generation.: No such file or directory (os error 2)                                                                                       
Failed to install bootloader                                                                                                                                
warning: …
=> fix(tool): better error if public key is missing

rust/tool/systemd/src/version.rs
In systemd 257.1, which is currently on staging-next in nixpkgs, systemd-boot no longer terminates its PE sections with null bytes: https://github.com/systemd/systemd/pull/34950. This leads to an error when installing Lanzaboote:
```
Installing Lanzaboote to "/boot"...
Failed to read systemd-boot version from "/nix/store/qz2c1an9hyg1paah2xx6d1fdllq0lw09-systemd-257.1/lib/systemd/boot/efi/systemd-bootx64.efi".: Failed to parse C string.: data provided is not nul terminated
Failed to install bootloader
```
This change has us check the last byte of the section, expecting either a NUL or a newline, and then we create a `&str` from that accordingly.
I tested this on two machines: one with staging-next and one with nixos-unstable, and both were able to install Lanzaboote successfully.
=> fix(tool): parse osrel sections without trailing null

README.md
In #440, I forgot to remove some stale references in the README to the removed fat stub.
=> Remove Stale References to Fat Stub

rust/tool/systemd/src/install.rs
```
Installing Lanzaboote to "/boot"...
$"/boot/EFI/BOOT/BOOTX64.EFI" is not signed. Replacing it with a signed binary... $"/boot/EFI/systemd/systemd-bootx64.efi" is not signed. Replacing it with a signed binary... Collecting garbage...
```
=> Remove rogue dollar sign
