nix-community/lanzaboote

- flake.nix
This adds a test for systemd stage 1, which pass.
> lanzaboot: test systemd stage 1

- default.nix
- flake.lock
- flake.nix
I will maintain this as I do not plan to move to Flakes yet.
> chore: support non-flake users

- rust/lanzatool/src/esp.rs
- rust/lanzatool/src/generation.rs
- rust/lanzatool/src/pe.rs
- rust/lanzatool/src/signature.rs
This PR contains various little fixes for lanzatool that surfaced during work on #34.
> Lanzatool: small fixes

- rust/lanzatool/src/gc.rs
- rust/lanzatool/src/install.rs
- rust/lanzatool/tests/gc.rs
This should fix #46. 
Depends on #48.
> Lanzatool: fix config limit

- nix/modules/lanzaboote.nix
- rust/lanzatool/Cargo.lock
- rust/lanzatool/Cargo.toml
- rust/lanzatool/src/generation.rs
- rust/lanzatool/src/install.rs
- rust/lanzatool/src/main.rs
- rust/lanzatool/src/os_release.rs
- rust/lanzatool/tests/common/mod.rs
- rust/lanzatool/tests/os_release.rs
Generate a custom os-release to provide nice boot menu entries for systemd-boot.
> Lanzatool: generate custom os-release

- rust/lanzatool/src/esp.rs
- rust/lanzatool/src/generation.rs
This drove me a little insane, so I changed it.
> Lanzatool: spell specialised consistently

- .gitignore
- flake.lock
- flake.nix
Building on top of #52, this PR enforces nixpkgs-fmt style on our Nix files via pre-commit. This is also checked via CI.
Please review commit-by-commit.
> Enforce Nix Style

- rust/tool/src/esp.rs
- rust/tool/src/install.rs
To access paths on the ESP before or after installing generations, split EspPaths into general EspPaths that only depend on the path to the ESP and EspGenerationPaths which additionally depend on generation specific information (e.g. version number and initrd filename).
This refactoring is in preparation to a larger change to the way systemd-boot is installed.
> tool: split esp paths

- nix/tests/lanzaboote.nix
The test attributes and names are simplified and standardized. They now roughly follow the same structure as the systemd-boot test in Nixpkgs. Some comments are added and variable names changed to make it more clear what they actually do.
> nix.tests: clean up

- rust/tool/src/install.rs
To minimize the potential for irrecoverable errors, only atomic writes to the ESP are performed. This is implemented by first copying the file to the destination with a `.tmp` suffix and then renaming it to the final desintation. This is atomic because the rename operation is atomic on POSIX platforms.
~~Specifically, this means that even if the system crashes during the operation, the final desintation path will **always** be intact if it exists at all.~~
Specifically, this means that even if the system crashes during the operation, the final desintation path will most likely be intact if it
exists at all. There are some nuances to this however. It **cannot** be actually guaranteed that the operation was performed on the filesystem level. However, this is the best we can do for now.
For …
> tool: atomically write to ESP

- rust/tool/src/os_release.rs
Closes #77
I hope this is more (or fully) correct now
> Make the os-release parser more precise

- nix/modules/lanzaboote.nix
Signed-off-by: ercao <vip@ercao.cn>
> nixos/lanzaboote: use `config.systemd.package`

- rust/tool/src/install.rs
> tool: fix typos

- docs/QUICK_START.md
> docs: add non-flakes quick start documentation

- rust/tool/src/install.rs
This change fine tunes some log messages.
> tool: fine tune a few log messages

- rust/tool/src/generation.rs
- rust/tool/tests/common/mod.rs
- rust/tool/tests/os_release.rs
> Use birth time instead of modify time for generation "built on" date

- nix/modules/lanzaboote.nix
Since there were open comments still at https://github.com/nix-community/lanzaboote/pull/131#pullrequestreview-1345125430 when #131 was merged, I'm opening this PR to allow further feedback from @dasJ on the proposed diff whenever they get a chance (no rush though!)
Primarily it removes the `mkdir` call in favor of letting systemd handle the `/run` directory lifetime and symlinks in `fwupdx64.efi` instead of copying it (since linking works just fine)
> nix: clean up fwupd-efi handling a little bit

- rust/tool/src/install.rs
Tells the user which generations are malformed and how to remove them.
Follow up to #161 to implement the improvements discussed there.
> tool: improve log message about malformed gens

- flake.nix
- rust/stub/src/efivars.rs
- rust/stub/src/main.rs
- rust/tool/src/generation.rs
- rust/tool/src/os_release.rs
Also formats the stub and tool in separate commits.
> Add rustfmt checks

- README.md
Fixes the rendering of README.
> docs: fixup stray ```

- docs/QUICK_START.md
> Further updates to QUICK_START.md

- rust/uefi/Cargo.lock
- rust/uefi/linux-bootloader/Cargo.toml
- rust/uefi/linux-bootloader/src/tpm.rs
TPM 1 will not be supported by newer systemd versions and is not widely
available anyways.
> stub: remove TPM 1 support

- rust/uefi/linux-bootloader/src/linux_loader.rs
While working on #194, I noticed some small room for improvement.
`*const T` and `Option<&T>` have the [same ABI](https://doc.rust-lang.org/reference/type-layout.html), so we can gain some 
more Rust convenience by using it.
Further, a bug is fixed where INVALID_PARAMETER wasn't returned when the BUFFER_SIZE pointer is NULL.
See UEFI 2.10 13.2.2. EFI_LOAD_FILE2_PROTOCOL.LoadFile() for reference.
> linux_loader: improve code quality + bug fix

- rust/tool/systemd/src/version.rs
Our systemd version parser chokes on versions, such as "255-rc2". Switch to regex parsing so we can easily handle this as well.
> Parse Systemd Release Candidate Versions

- rust/tool/shared/src/os_release.rs
This tries to fix https://github.com/nix-community/lanzaboote/issues/77 by porting the [original parser function](https://github.com/systemd/systemd/blob/9ef362bf3d16d9929045c2f64af9e7dd9357dbb0/src/basic/env-file.c#L22) to rust.
You can follow the path from the test function to the parser function:
1. The tests are defined [here](https://github.com/systemd/systemd/blob/9ef362bf3d16d9929045c2f64af9e7dd9357dbb0/src/test/test-os-util.c#L22)
2. The macro for the function [here](https://github.com/systemd/systemd/blob/9ef362bf3d16d9929045c2f64af9e7dd9357dbb0/src/basic/os-util.h#L42)
3. The function that open the file [here](https://github.com/systemd/systemd/blob/9ef362bf3d16d9929045c2f64af9e7dd9357dbb0/src/basic/os-util.c#L336)
4. The function that handle some internal stuff …
> Use the original os-release file parser

- flake.nix
This dependency brings in a lot of other dependencies including a nixpkgs copy. By making it optional in the flake users can disable it in their own flake.
After removing the dependency, the following inputs are no longer needed:
• Removed input 'pre-commit-hooks-nix'
• Removed input 'pre-commit-hooks-nix/flake-compat' 
• Removed input 'pre-commit-hooks-nix/flake-utils' 
• Removed input 'pre-commit-hooks-nix/gitignore'
• Removed input 'pre-commit-hooks-nix/gitignore/nixpkgs' 
• Removed input 'pre-commit-hooks-nix/nixpkgs'
• Removed input 'pre-commit-hooks-nix/nixpkgs-stable'
> make pre-commit-hooks-nix optional

- README.md
> readme: make upstreaming section more timeless

- flake.lock
- rust/tool/Cargo.lock
- rust/uefi/Cargo.lock
Reverts nix-community/lanzaboote#289
> Revert "chore(deps): lock file maintenance"

- docs/QUICK_START.md
I and some others have had this issue on the Nix Community Discord and the Matrix Room!
> readme: add mention of "Window UEFI Mode" needed on some boards

- docs/QUICK_START.md
I've just went through the setup process on my Framework laptop and fixed some nits in the quick start docs.
> Add more framework-specific hints

- nix/modules/lanzaboote.nix
> module: revert sort-key from lanzaboote back to lanza

- docs/QUICK_START.md
Credit: https://codebenchers.com/blog/secure-boot-nixos-surface-go3
> Add note for Microsoft Surface devices to QUICK_START.md
